const pages=[
{en:['Pizza','Hand-stretched dough, baked fresh to order.',[['Margherita Pizza','120 EGP','Tomato sauce, mozzarella, basil'],['Pepperoni Pizza','160 EGP','Pepperoni, mozzarella, tomato sauce'],['Chicken Ranch Pizza','170 EGP','Chicken, ranch sauce, mozzarella'],['BBQ Chicken Pizza','175 EGP','Smoky BBQ chicken, red onion, mozzarella'],['Four Cheese Pizza','180 EGP','Mozzarella, parmesan, cheddar, blue cheese']]],ar:['البيتزا','عجين طازج يُفرد باليد ويُخبز عند الطلب.',[['بيتزا مارغريتا','١٢٠ ج.م','صلصة طماطم، موتزاريلا، ريحان'],['بيتزا بيبروني','١٦٠ ج.م','بيبروني، موتزاريلا، صلصة طماطم'],['بيتزا دجاج رانش','١٧٠ ج.م','دجاج، صلصة رانش، موتزاريلا'],['بيتزا دجاج باربكيو','١٧٥ ج.م','دجاج باربكيو، بصل أحمر، موتزاريلا'],['بيتزا أربع جبنات','١٨٠ ج.م','موتزاريلا، بارميزان، شيدر، جبنة زرقاء']]]},
{en:['Pasta & Bites','Comforting classics for every kind of appetite.',[['Creamy Chicken Pasta','150 EGP','Penne, chicken, mushroom cream sauce'],['Spicy Arrabbiata','125 EGP','Penne in spicy tomato and garlic sauce'],['Garlic Bread','55 EGP','Toasted bread, garlic butter, herbs'],['Mozzarella Sticks','85 EGP','Crispy coating with marinara dip'],['Chicken Wings','115 EGP','Six wings, your choice of BBQ or spicy sauce']]],ar:['الباستا والمقبلات','أطباق مريحة وشهية لكل الأذواق.',[['باستا دجاج بالكريمة','١٥٠ ج.م','بيني، دجاج، فطر، صلصة كريمية'],['أرابياتا حارة','١٢٥ ج.م','بيني بصلصة طماطم حارة وثوم'],['خبز بالثوم','٥٥ ج.م','خبز محمص، زبدة ثوم، أعشاب'],['أصابع موتزاريلا','٨٥ ج.م','مقرمشة مع صوص مارينارا'],['أجنحة دجاج','١١٥ ج.م','ست قطع بصوص باربكيو أو حار']]]},
{en:['Drinks & Sweet','A bright finish for your POSsible Pizza moment.',[['Fresh Lemon Mint','55 EGP','Fresh lemon, mint and crushed ice'],['Strawberry Mojito','65 EGP','Strawberry, lime, mint, soda'],['Classic Tiramisu','95 EGP','Espresso-soaked biscuit and mascarpone'],['Chocolate Brownie','85 EGP','Warm brownie with a scoop of vanilla'],['Soft Drink','35 EGP','Coke, Sprite or Fanta']]],ar:['المشروبات والحلويات','نهاية جميلة للحظة POSsible Pizza الخاصة بك.',[['ليمون بالنعناع','٥٥ ج.م','ليمون طازج، نعناع وثلج مجروش'],['موهيتو فراولة','٦٥ ج.م','فراولة، ليمون، نعناع وصودا'],['تيراميسو كلاسيك','٩٥ ج.م','بسكويت بالإسبريسو وكريمة ماسكاربوني'],['براوني بالشوكولاتة','٨٥ ج.م','براوني دافئ مع آيس كريم فانيليا'],['مشروب غازي','٣٥ ج.م','كوكاكولا، سبرايت أو فانتا']]]}
];
const text={en:['Fresh from the oven','Our Menu','Made with good ingredients, served with a little possibility.','Previous','Next','SECTION'],ar:['طازج من الفرن','قائمتنا','مصنوع بمكونات جيدة، ويُقدم مع لمسة من الإمكانات.','السابق','التالي','القسم']};let lang='en',spread=0,turning=false;const $=s=>document.querySelector(s);const mobile=()=>matchMedia('(max-width: 680px)').matches;
function markup(index){const [title,note,items]=pages[index][lang];return `<div class="menu-page-content"><p class="section-number">${text[lang][5]} ${String(index+1).padStart(2,'0')}</p><h2>${title}</h2><p class="section-note">${note}</p><ul class="menu-list">${items.map(([n,p,d])=>`<li class="menu-item"><div class="item-line"><span class="item-name">${n}</span><span class="item-price">${p}</span></div><p class="item-description">${d}</p></li>`).join('')}</ul><span class="page-footer">POSsible Pizza · ${index+1}</span></div>`}
function render(){const left=mobile()?spread:spread*2,right=left+1,total=mobile()?pages.length:Math.ceil(pages.length/2);$('#left-page').innerHTML=markup(left);$('#right-page').innerHTML=right<pages.length?markup(right):`<div class="menu-page-content"><p class="section-number">POSsible Pizza</p><h2>${lang==='ar'?'شهية طيبة':'Enjoy your meal'}</h2><p class="section-note">${lang==='ar'?'نراكم قريباً.':'See you again soon.'}</p></div>`;$('#page-count').textContent=`${spread+1} / ${total}`;$('#previous-page').disabled=spread===0;$('#next-page').disabled=spread===total-1;const t=text[lang];$('#eyebrow').textContent=t[0];$('#menu-heading').textContent=t[1];$('#intro-copy').textContent=t[2];$('#previous-label').textContent=t[3];$('#next-label').textContent=t[4]}
function turn(direction){if(turning)return;const max=(mobile()?pages.length:Math.ceil(pages.length/2))-1,target=spread+direction;if(target<0||target>max)return;turning=true;spread=target;render();const sheet=$('#turn-sheet');sheet.className=`turn-sheet ${(direction>0)!==(lang==='ar')?'forward':'backward'}`;sheet.addEventListener('animationend',()=>{sheet.className='turn-sheet';turning=false},{once:true})}
$('#previous-page').onclick=()=>turn(-1);$('#next-page').onclick=()=>turn(1);$('#language-toggle').onclick=()=>{lang=lang==='en'?'ar':'en';document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.classList.toggle('rtl',lang==='ar');$('#language-toggle').textContent=lang==='en'?'العربية':'English';spread=0;render()};addEventListener('resize',()=>{spread=0;render()});render();
const book = $('#menu-book-pages');
let startX = 0, dragX = 0, pointerActive = false;
book.addEventListener('pointerdown', event => { if (turning) return; pointerActive = true; startX = event.clientX; dragX = 0; book.setPointerCapture(event.pointerId); book.classList.add('is-dragging'); });
book.addEventListener('pointermove', event => { if (!pointerActive) return; dragX = event.clientX - startX; book.style.setProperty('--drag', Math.max(-45, Math.min(45, dragX / 3))); });
function finishDrag(event) { if (!pointerActive) return; pointerActive = false; book.classList.remove('is-dragging'); book.style.removeProperty('--drag'); if (Math.abs(dragX) > 65) turn((lang === 'ar' ? dragX > 0 : dragX < 0) ? 1 : -1); if (book.hasPointerCapture(event.pointerId)) book.releasePointerCapture(event.pointerId); }
book.addEventListener('pointerup', finishDrag); book.addEventListener('pointercancel', finishDrag);

function updateFooter(){const footerText=document.querySelector('#copyright');if(footerText)footerText.textContent=lang==='ar'?'© 2026 POSsible. جميع الحقوق محفوظة.':'© 2026 POSsible. All rights reserved.'}updateFooter();document.querySelector('#language-toggle').addEventListener('click',updateFooter);
const pagePhotos=['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1400&q=80','https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1400&q=80','https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1400&q=80'];
function applyPagePhotos(){const left=mobile()?spread:spread*2,right=left+1;document.querySelector('#left-page').style.setProperty('--page-photo',`url("${pagePhotos[left]}")`);document.querySelector('#right-page').style.setProperty('--page-photo',right<pagePhotos.length?`url("${pagePhotos[right]}")`:'none');}
applyPagePhotos();new MutationObserver(applyPagePhotos).observe(document.querySelector('#menu-book-pages'),{childList:true,subtree:true});
const themeButton=document.querySelector('#theme-toggle');function setTheme(theme){document.body.classList.toggle('dark-mode',theme==='dark');themeButton.firstElementChild.textContent=theme==='dark'?'☀':'☾';localStorage.setItem('possible-theme',theme);}setTheme(localStorage.getItem('possible-theme')||'light');themeButton.addEventListener('click',()=>setTheme(document.body.classList.contains('dark-mode')?'light':'dark'));
// Cart configuration
const restaurantConfig={name:'POSsible Pizza',whatsapp:'201026779104',currency:'EGP',storageKey:'possible-pizza-cart'};
var pizzaCart=JSON.parse(localStorage.getItem(restaurantConfig.storageKey)||'[]');
function cartText(){return lang==='ar'?{add:'أضف للسلة',cart:'السلة',empty:'سلتك فارغة.',check:'إتمام الطلب',total:'الإجمالي',remove:'حذف'}:{add:'Add to Cart',cart:'Your cart',empty:'Your cart is empty.',check:'Checkout',total:'Total',remove:'Remove'}}
function product(id){let m=/^pizza-(\d+)-(\d+)$/.exec(id),x=m&&pages[+m[1]]?.en[2][+m[2]];return x&&{id,page:+m[1],item:+m[2],price:parseInt(x[1])}}function itemName(p){return pages[p.page][lang][2][p.item][0]}function total(){return pizzaCart.reduce((s,x)=>{let p=product(x.id);return s+(p?p.price*x.quantity:0)},0)}function price(n){return n+' '+restaurantConfig.currency}
function save(){localStorage.setItem(restaurantConfig.storageKey,JSON.stringify(pizzaCart))}function addToCart(id){let x=pizzaCart.find(x=>x.id===id);x?x.quantity++:pizzaCart.push({id,quantity:1});save();renderCart()}function removeFromCart(id){pizzaCart=pizzaCart.filter(x=>x.id!==id);save();renderCart()}function increaseQuantity(id){addToCart(id)}function decreaseQuantity(id){let x=pizzaCart.find(x=>x.id===id);if(x)x.quantity===1?removeFromCart(id):(x.quantity--,save(),renderCart())}
function renderCart(){let t=cartText();$('#cart-items').innerHTML=pizzaCart.length?pizzaCart.map(x=>{let p=product(x.id);return '<article class="cart-item"><div><strong>'+itemName(p)+'</strong><span>'+price(p.price)+'</span><div class="quantity-controls"><button data-c="-" data-id="'+x.id+'">−</button><b>'+x.quantity+'</b><button data-c="+" data-id="'+x.id+'">+</button><button class="remove-item" data-c="x" data-id="'+x.id+'">'+t.remove+'</button></div></div><strong>'+price(p.price*x.quantity)+'</strong></article>'}).join(''):'<p class="empty-cart">'+t.empty+'</p>';$('#cart-title').textContent=t.cart;$('#cart-total').textContent=price(total());$('#checkout-button').textContent=t.check;$('#checkout-button').disabled=!pizzaCart.length;let b=$('#cart-badge'),n=pizzaCart.reduce((s,x)=>s+x.quantity,0);b.textContent=n;b.hidden=!n}
function markup(index){let [title,note,items]=pages[index][lang];return '<div class="menu-page-content"><p class="section-number">'+text[lang][5]+' '+String(index+1).padStart(2,'0')+'</p><h2>'+title+'</h2><p class="section-note">'+note+'</p><ul class="menu-list">'+items.map(([n,p,d],i)=>'<li class="menu-item"><div class="item-line"><span class="item-name">'+n+'</span><span class="item-price">'+p+'</span></div><p class="item-description">'+d+'</p><button class="add-to-cart" data-product-id="pizza-'+index+'-'+i+'">'+cartText().add+'</button></li>').join('')+'</ul><span class="page-footer">POSsible Pizza · '+(index+1)+'</span></div>'}
function openCart(){renderCart();$('#cart-layer').classList.add('is-open')}function closeCart(){$('#cart-layer').classList.remove('is-open')}function openCheckout(){if(!pizzaCart.length)return;closeCart();let t=cartText();$('#summary-items').innerHTML=pizzaCart.map(x=>{let p=product(x.id);return '<div class="summary-line"><span>'+x.quantity+' × '+itemName(p)+'</span><strong>'+price(p.price*x.quantity)+'</strong></div>'}).join('');$('#summary-total').textContent=price(total());$('#checkout-layer').classList.add('is-open')}function closeCheckout(){$('#checkout-layer').classList.remove('is-open')}
function submitOrder(e){e.preventDefault();let d=Object.fromEntries(new FormData(e.currentTarget));if(!d.customerName||!d.tableNumber)return;let lines=pizzaCart.map(x=>{let p=product(x.id);return x.quantity+'x '+itemName(p)+' — '+price(x.quantity*p.price)}).join('\n'),m='New Order – '+restaurantConfig.name+'\n\nCustomer: '+d.customerName+'\nTable: '+d.tableNumber+'\nOrder Type: '+d.orderType+'\n\nOrder:\n'+lines+'\n\nNotes:\n'+(d.notes||'-')+'\n\nTotal: '+price(total());window.open('https://wa.me/'+restaurantConfig.whatsapp+'?text='+encodeURIComponent(m),'_blank','noopener');pizzaCart=[];save();closeCheckout();renderCart()}
$('#menu-book-pages').addEventListener('click',e=>{let b=e.target.closest('.add-to-cart');if(b)addToCart(b.dataset.productId)});$('#cart-toggle').onclick=openCart;document.querySelectorAll('[data-cart-close]').forEach(x=>x.onclick=closeCart);document.querySelectorAll('[data-checkout-close]').forEach(x=>x.onclick=closeCheckout);$('#checkout-button').onclick=openCheckout;$('#cart-items').onclick=e=>{let b=e.target.closest('[data-c]');if(b)b.dataset.c==='+'?increaseQuantity(b.dataset.id):b.dataset.c==='-'?decreaseQuantity(b.dataset.id):removeFromCart(b.dataset.id)};$('#checkout-form').onsubmit=submitOrder;$('#language-toggle').addEventListener('click',()=>{renderCart()});render();renderCart();

function itemQuantity(id){return Array.isArray(pizzaCart)?pizzaCart.find(x=>x.id===id)?.quantity||0:0}
function markup(index){let [title,note,items]=pages[index][lang];return '<div class="menu-page-content"><p class="section-number">'+text[lang][5]+' '+String(index+1).padStart(2,'0')+'</p><h2>'+title+'</h2><p class="section-note">'+note+'</p><ul class="menu-list">'+items.map(([n,p,d],i)=>{let id='pizza-'+index+'-'+i,q=itemQuantity(id);return '<li class="menu-item"><div class="item-line"><span class="item-name">'+n+'</span><span class="item-price">'+p+'</span></div><p class="item-description">'+d+'</p><div class="item-cart-controls"><button class="item-quantity-button" type="button" data-menu-action="decrease" data-product-id="'+id+'" aria-label="Decrease quantity">−</button><strong class="item-quantity">'+q+'</strong><button class="item-quantity-button" type="button" data-menu-action="increase" data-product-id="'+id+'" aria-label="Increase quantity">+</button><button class="add-to-cart" type="button" data-menu-action="add" data-product-id="'+id+'">'+cartText().add+'</button></div></li>'}).join('')+'</ul><span class="page-footer">POSsible Pizza · '+(index+1)+'</span></div>'}
document.addEventListener('click',event=>{const button=event.target.closest('[data-menu-action]');if(!button)return;event.preventDefault();event.stopPropagation();const id=button.dataset.productId,action=button.dataset.menuAction;if(action==='add'||action==='increase')addToCart(id);if(action==='decrease')decreaseQuantity(id);render()},{capture:true});

function generateOrderId(){const now=new Date(),date=now.getFullYear()+String(now.getMonth()+1).padStart(2,'0')+String(now.getDate()).padStart(2,'0'),time=String(now.getHours()).padStart(2,'0')+String(now.getMinutes()).padStart(2,'0')+String(now.getSeconds()).padStart(2,'0'),suffix=Math.random().toString(36).slice(2,5).toUpperCase();return 'PP-'+date+'-'+time+'-'+suffix'}
function submitOrder(e){e.preventDefault();let d=Object.fromEntries(new FormData(e.currentTarget));if(!d.customerName||!d.tableNumber)return;let orderId=generateOrderId(),pfx=lang==='ar'?'رقم الطلب':'Order ID',lines=pizzaCart.map(x=>{let p=product(x.id);return x.quantity+'x '+itemName(p)+' — '+price(x.quantity*p.price)}).join('\n'),m='New Order – '+restaurantConfig.name+'\n'+pfx+': '+orderId+'\n\nCustomer: '+d.customerName+'\nTable: '+d.tableNumber+'\nOrder Type: '+d.orderType+'\n\nOrder:\n'+lines+'\n\nNotes:\n'+(d.notes||'-')+'\n\nTotal: '+price(total());window.open('https://wa.me/'+restaurantConfig.whatsapp+'?text='+encodeURIComponent(m),'_blank','noopener');pizzaCart=[];save();closeCheckout();renderCart()}
render();
