const pages=[
{en:['Pizza','Hand-stretched dough, baked fresh to order.',[['Margherita Pizza','120 EGP','Tomato sauce, mozzarella, basil'],['Pepperoni Pizza','160 EGP','Pepperoni, mozzarella, tomato sauce'],['Chicken Ranch Pizza','170 EGP','Chicken, ranch sauce, mozzarella'],['BBQ Chicken Pizza','175 EGP','Smoky BBQ chicken, red onion, mozzarella'],['Four Cheese Pizza','180 EGP','Mozzarella, parmesan, cheddar, blue cheese']]],ar:['البيتزا','عجين طازج يُفرد باليد ويُخبز عند الطلب.',[['بيتزا مارغريتا','١٢٠ ج.م','صلصة طماطم، موتزاريلا، ريحان'],['بيتزا بيبروني','١٦٠ ج.م','بيبروني، موتزاريلا، صلصة طماطم'],['بيتزا دجاج رانش','١٧٠ ج.م','دجاج، صلصة رانش، موتزاريلا'],['بيتزا دجاج باربكيو','١٧٥ ج.م','دجاج باربكيو، بصل أحمر، موتزاريلا'],['بيتزا أربع جبنات','١٨٠ ج.م','موتزاريلا، بارميزان، شيدر، جبنة زرقاء']]]},
{en:['Pasta & Bites','Comforting classics for every kind of appetite.',[['Creamy Chicken Pasta','150 EGP','Penne, chicken, mushroom cream sauce'],['Spicy Arrabbiata','125 EGP','Penne in spicy tomato and garlic sauce'],['Garlic Bread','55 EGP','Toasted bread, garlic butter, herbs'],['Mozzarella Sticks','85 EGP','Crispy coating with marinara dip'],['Chicken Wings','115 EGP','Six wings, your choice of BBQ or spicy sauce']]],ar:['الباستا والمقبلات','أطباق مريحة وشهية لكل الأذواق.',[['باستا دجاج بالكريمة','١٥٠ ج.م','بيني، دجاج، فطر، صلصة كريمية'],['أرابياتا حارة','١٢٥ ج.م','بيني بصلصة طماطم حارة وثوم'],['خبز بالثوم','٥٥ ج.م','خبز محمص، زبدة ثوم، أعشاب'],['أصابع موتزاريلا','٨٥ ج.م','مقرمشة مع صوص مارينارا'],['أجنحة دجاج','١١٥ ج.م','ست قطع بصوص باربكيو أو حار']]]},
{en:['Drinks & Sweet','A bright finish for your POSsible Pizza moment.',[['Fresh Lemon Mint','55 EGP','Fresh lemon, mint and crushed ice'],['Strawberry Mojito','65 EGP','Strawberry, lime, mint, soda'],['Classic Tiramisu','95 EGP','Espresso-soaked biscuit and mascarpone'],['Chocolate Brownie','85 EGP','Warm brownie with a scoop of vanilla'],['Soft Drink','35 EGP','Coke, Sprite or Fanta']]],ar:['المشروبات والحلويات','نهاية جميلة للحظة POSsible Pizza الخاصة بك.',[['ليمون بالنعناع','٥٥ ج.م','ليمون طازج، نعناع وثلج مجروش'],['موهيتو فراولة','٦٥ ج.م','فراولة، ليمون، نعناع وصودا'],['تيراميسو كلاسيك','٩٥ ج.م','بسكويت بالإسبريسو وكريمة ماسكاربوني'],['براوني بالشوكولاتة','٨٥ ج.م','براوني دافئ مع آيس كريم فانيليا'],['مشروب غازي','٣٥ ج.م','كوكاكولا، سبرايت أو فانتا']]]}
];
const text={en:['Fresh from the oven','Our Menu','Made with good ingredients, served with a little possibility.','Previous','Next','SECTION'],ar:['طازج من الفرن','قائمتنا','مصنوع بمكونات جيدة، ويُقدم مع لمسة من الإمكانات.','السابق','التالي','القسم']};let lang='en',spread=0,turning=false;const $=s=>document.querySelector(s);const mobile=()=>matchMedia('(max-width: 680px)').matches;
function markup(index){const [title,note,items]=pages[index][lang];return `<div class="menu-page-content"><p class="section-number">${text[lang][5]} ${String(index+1).padStart(2,'0')}</p><h2>${title}</h2><p class="section-note">${note}</p><ul class="menu-list">${items.map(([n,p,d])=>`<li class="menu-item"><div class="item-line"><span class="item-name">${n}</span><span class="item-price">${p}</span></div><p class="item-description">${d}</p></li>`).join('')}</ul><span class="page-footer">POSsible Pizza · ${index+1}</span></div>`}
function render(){const left=mobile()?spread:spread*2,right=left+1,total=mobile()?pages.length:Math.ceil(pages.length/2);$('#left-page').innerHTML=markup(left);$('#right-page').innerHTML=right<pages.length?markup(right):`<div class="menu-page-content"><p class="section-number">POSsible Pizza</p><h2>${lang==='ar'?'شهية طيبة':'Enjoy your meal'}</h2><p class="section-note">${lang==='ar'?'نراكم قريباً.':'See you again soon.'}</p></div>`;$('#page-count').textContent=`${spread+1} / ${total}`;$('#previous-page').disabled=spread===0;$('#next-page').disabled=spread===total-1;const t=text[lang];$('#eyebrow').textContent=t[0];$('#menu-heading').textContent=t[1];$('#intro-copy').textContent=t[2];$('#previous-label').textContent=t[3];$('#next-label').textContent=t[4]}
function turn(direction){if(turning)return;const max=(mobile()?pages.length:Math.ceil(pages.length/2))-1,target=spread+direction;if(target<0||target>max)return;turning=true;spread=target;render();const sheet=$('#turn-sheet');sheet.className=`turn-sheet ${(direction>0)!==(lang==='ar')?'forward':'backward'}`;sheet.addEventListener('animationend',()=>{sheet.className='turn-sheet';turning=false},{once:true})}
$('#previous-page').onclick=()=>turn(-1);$('#next-page').onclick=()=>turn(1);$('#language-toggle').onclick=()=>{lang=lang==='en'?'ar':'en';document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.classList.toggle('rtl',lang==='ar');$('#language-toggle').textContent=lang==='en'?'العربية':'English';spread=0;render()};addEventListener('resize',()=>{spread=0;render()});render();
const book = $('#menu-book-pages');
let startX = 0, dragX = 0, pointerActive = false;
book.addEventListener('pointerdown', event => { if (turning) return; pointerActive = true; startX = event.clientX; dragX = 0; book.setPointerCapture(event.pointerId); book.classList.add('is-dragging'); });
book.addEventListener('pointermove', event => { if (!pointerActive) return; dragX = event.clientX - startX; book.style.setProperty('--drag', Math.max(-45, Math.min(45, dragX / 3))); });
function finishDrag(event) { if (!pointerActive) return; pointerActive = false; book.classList.remove('is-dragging'); book.style.removeProperty('--drag'); if (Math.abs(dragX) > 65) turn((lang === 'ar' ? dragX > 0 : dragX < 0) ? 1 : -1); if (book.hasPointerCapture(event.pointerId)) book.releasePointerCapture(event.pointerId); }
book.addEventListener('pointerup', finishDrag); book.addEventListener('pointercancel', finishDrag);

function updateFooter(){const footerText=document.querySelector('#copyright');if(footerText)footerText.textContent=lang==='ar'?'© 2026 POSsible. جميع الحقوق محفوظة.':'© 2026 POSsible. All rights reserved.'}updateFooter();document.querySelector('#language-toggle').addEventListener('click',updateFooter);
